//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xml.Schema.Linq.Xunit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xml.Schema.Linq.Xunit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema
        ///	xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	targetNamespace=&quot;A&quot;
        ///	xmlns:A=&quot;A&quot;&gt;
        ///
        ///  &lt;xs:element name=&quot;account&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:attribute ref=&quot;A:account&quot;/&gt;
        ///    &lt;/xs:complexType&gt;
        ///  &lt;/xs:element&gt;
        ///
        ///  &lt;xs:attribute name=&quot;account&quot;&gt;
        ///    &lt;xs:simpleType&gt;
        ///      &lt;xs:union memberTypes=&quot;xs:string&quot; /&gt;
        ///    &lt;/xs:simpleType&gt;
        ///  &lt;/xs:attribute&gt;
        ///
        ///&lt;/xs:schema&gt;.
        /// </summary>
        internal static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema
        ///	xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	targetNamespace=&quot;A&quot;
        ///	xmlns:A=&quot;A&quot;&gt;
        ///
        ///  &lt;xs:element name=&quot;account&quot;&gt;
        ///    &lt;xs:simpleType&gt;
        ///      &lt;xs:union memberTypes=&quot;xs:string&quot; /&gt;
        ///    &lt;/xs:simpleType&gt;
        ///  &lt;/xs:element&gt;
        ///
        ///&lt;/xs:schema&gt;.
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema
        ///	xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	targetNamespace=&quot;A&quot;
        ///	xmlns:A=&quot;A&quot;&gt;
        ///
        ///  &lt;xs:element name=&quot;account&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:attribute ref=&quot;A:account&quot;/&gt;
        ///    &lt;/xs:complexType&gt;
        ///  &lt;/xs:element&gt;
        ///
        ///  &lt;xs:attribute name=&quot;account&quot; type=&quot;A:my&quot;/&gt;
        ///
        ///  &lt;xs:simpleType name=&quot;my&quot;&gt;
        ///    &lt;xs:union memberTypes=&quot;xs:string&quot; /&gt;
        ///  &lt;/xs:simpleType&gt;
        ///
        ///&lt;/xs:schema&gt;.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema
        ///	xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	targetNamespace=&quot;A&quot;
        ///	xmlns:A=&quot;A&quot;&gt;
        ///
        ///  &lt;xs:element name=&quot;account&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:attribute ref=&quot;A:account&quot;/&gt;
        ///    &lt;/xs:complexType&gt;
        ///  &lt;/xs:element&gt;
        ///
        ///  &lt;xs:attribute name=&quot;account&quot;&gt;
        ///    &lt;xs:simpleType&gt;
        ///      &lt;xs:union memberTypes=&quot;A:type1 A:type2&quot; /&gt;
        ///    &lt;/xs:simpleType&gt;
        ///  &lt;/xs:attribute&gt;
        ///
        ///  &lt;xs:simpleType name=&quot;type1&quot;&gt;
        ///    &lt;xs:restriction base=&quot;xs:string&quot;&gt;
        ///      &lt;xs:pattern value [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Union {
            get {
                return ResourceManager.GetString("Union", resourceCulture);
            }
        }
    }
}
